### ISSUE TITLE
Cannot find module './dist/ordinales' from 'node_modules/ordinales-js/index.js'

### ISSUE THREAD

**Issue by SaidTorres3** [AndresSaa/ordinales-js#10]
Step 0: npm i ordinales-js@1.0.6
Step 1: const ordinales = require("ordinales-js");
Step 2: Run.

Error: ```Cannot find module './dist/ordinales' from 'node_modules/ordinales-js/index.js'```

**Comment by AndresSaa** [comment]
Hi @SaidTorres3 you need to use the latest version: ordinales-js@1.0.15
